---
title: 最小上界性和最大下界性的等价
author: 冯冬发
date: '2021-09-27'
slug: least_upper_bound_property
categories:
  - 数学分析
tags:
  - 阅读笔记
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{ctex}
---
## 定理
摘自《普林斯顿数学分析读本》的定理$4.12$和定理$4.13$。

> **定理 4.12** 
设$S$是具有最小上界性的有序集，
那么$S$也具有最大下界性。
也就是说，$S$的每一个有下界的非空子集$B$都在$S$中存在$\inf B$。
此外，如果设$L$为$B$的全体下界的集合，那么$\inf B=\sup L$。

> **定理 4.13** 
设$S$是具有最大下界性的有序集，
那么$S$也具有最小上界性。
也就是说，$S$的每一个有上界的非空子集$B$都在$S$中存在$\sup B$。
此外，如果设$U$为$B$的全体上界的集合，那么$\sup B=\inf U$。

## 证明定理$4.12$
依命题当中假设，
在拥有最小上界性的有序集$S$当中有一个存在下界的非空子集$B$。

先令集合$L$为集合$B$全体下界构成的集合，
由于集合$B$存在下界，则$L$为非空集合。
集合$L$当中的任意元素都是集合$B$的下界，
也就是说集合$L$当中的任意元素都不大于集合$B$当中的所有元素，
也就是说集合$B$当中的任意元素都不小于集合$L$当中的所有元素，
所以集合$B$当中的任意元素都是集合$L$的上界。

由于集合$B$非空，则集合$L$至少存在一个上界。
由于集合$S$具有最小上界性，则可推知$\sup L$存在。
不妨令$\alpha=\sup L$，
如果我们能够证明$\alpha=\inf B$，那么命题得证。

为证明$\alpha$为集合$B$的最大下界，我们首先要证明其为集合$B$的下界，
即$\alpha$不大于集合$B$当中的所有元素。
使用反证法证明，假设集合$B$当中存在某个元素$\gamma<\alpha$，
即$\gamma<\sup L$，
由上确界的定义可知$\gamma$不是集合$L$的上界，
即在集合$L$当中存在某个元素大于$\gamma$，
也就是说集合$L$当中存在某个元素大于集合$B$当中的某个元素，
这就和集合$L$是集合$B$全体下界的集合相矛盾，
故而$\alpha$是集合$B$的下界。

现在来证明$\alpha$是最大下界，对于任意的$\beta>\alpha$，
则有$\beta>\sup L$，
由上确界的定义可知$\beta\notin L$，即$\beta$不是$B$的下界，由此命题得证。

## 证明定理$4.13$
依葫芦画瓢，可以从最大下界性推出最小上界性。

由$B$存在上界可知$U$非空，由$B$非空可推知$U$存在下界，
两相结合由最大下界性推知$\alpha=\inf U$存在。

如果$\alpha$不是$B$的上界，则$B$中存在某个元素大于$\alpha$，
也就是说$B$中某个元素大于$U$的某个元素，这与集合$U$的定义相矛盾，
故而$\alpha$是$B$的上界。

对于任意$\beta<\alpha$，均有$\beta<\inf U$，会有$\beta\notin U$，
也就是说$\beta$不是$B$的上界，由此便证明了$\alpha=\sup B$。



