---
title: 实数域的基本性质
author: 冯冬发
date: '2021-09-28'
slug: real_field_basic_property
categories:
  - 数学分析
tags:
  - 阅读笔记
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{ctex}
---
## 实数域的定义
《普林斯顿数学分析读本》直接定义出一个实数域：

> **定义 5.4**
实数集$\mathbb{R}$是具有最小上界性且包含$\mathbb{Q}$的有序域。

为使本文具有一定的自包含性（self-contained），
我们首先将该定义当中提及的概念都摘抄出来：

- $\mathbb{Q}$是全体有理数的集合。
- 设$S$是有序集，如果$S$的每一个有上界的非空子集$E$都在$S$中存在$\sup E$，
那么称有序集$S$具有最小上界性。
- 如果集合$F$对加法运算和乘法运算闭合，则称其为域。
- 有序域是域，然后还是满足两条公理的有序集：
  - 如果$y<z$，那么$\forall x, y,z\in F$，$x+y<x+z$
  - 如果$x>0$且$y>0$，那么$\forall x,y\in F$，$xy>0$
  
我们的生活经验告诉我们实数域是存在的，
在这里我们直接假设实数域是存在的。
以后学有余力的话，可能会再将实数域存在性的证明过程摘抄下来。

## 实数域$\mathbb{R}$的阿基米德性质
### 定理
> 对于任意一个给定的正实数，我们都可以找到一个自然数，使得这两个数的乘积任意大。

> 用符号表示，即$\forall x,y\in\mathbb{R}$且$x>0$，
$\exists n\in\mathbb{N}$使得$nx>y$

### 证明
使用反证法可以证明该命题。

假设不存在$n\in\mathbb{N}$可以使得$nx>y$，
也就是说$y$是集合$A=\{nx|n\in\mathbb{N}\}$的上界。
由于实数域具有最小上界性，同时集合$A$非空且有上界，
由此可知集合$A$存在最小上界$\alpha=\sup A$。

那么对于数$\alpha-x$而言，该数小于$\alpha$，
由上确界的定义可知，该数不是集合$A$的上界，
则存在某个自然数$m$，使得$\alpha-x<mx$，即$\alpha<(m+1)x$成立。

由于$(m+1)x\in A$，则$\alpha$不为集合$A$的上界，
这与$\alpha$是$A$的上确界相矛盾，故而，我们认为命题成立。

## 有理数域$\mathbb{Q}$在实数域$\mathbb{R}$中稠密
### 定理
> 任意两个实数之间都至少存在一个有理数。

> 用符号表示，即：$x,y\in\mathbb{R}$且$x<y\Rightarrow\exists p\in\mathbb{Q}$使得$x<p<y$

### 证明
命题就是想在实数$x$和$y$之间找到一个有理数$m/n$，
我们首先要找到一个合适的$n$，
使得序列${1/n, 2/n,\ldots}$至少有一个元素落在$x$和$y$中间。
这就需要我们找到一个足够大的$n$，使得$1/n<y-x$成立，
即要求$n(y-x)>1$，这显然可以由实数域的阿基米德性质满足。

第二步便是要取到一个合适的$m$，使得$nx<m<ny$成立。
前文选择出来的$n$满足$ny>1+nx$，
如果我们可以找到一个满足$nx<m\le1+nx$的$m$，
那么就会有$nx<m\le1+nx<ny$，
我们就证明了原命题成立。
可以将条件$nx<m\le1+nx$改写为$m-1\le nx<m$。

第一种情形是$nx>0$，可以写出集合$\{m_1\in\mathbb{N}|m_1>nx\}$，
由实数的阿基米德性质可知该集合非空，
同时由良序定理可知该集合存在最小值$m$，
该最小值满足$m>nx$，同时$m-1$不在集合内，有$m-1\le nx$，
所以我们就找到了一个符合条件的$m$。

第二种情形是$nx=0$，直接取$m=1$便能满足$m-1\le nx<m$。

第三种情形是$nx<0$，那么会有$-nx>0$，参照第一种情形当中的讨论，
我们能够找到这样的一个自然数$m_2$，其满足$m_2-1\le -nx<m_2$。
进而有$-m_2<nx\le 1-m_2$。
如果$nx=1-m_2$，可以取$m=2-m_2$，有$m-1\le nx<m$成立。
如果$nx<1-m_2$，可以去$m=1-m_2$，同样有$m-1\le nx<m$成立。

综上所述，我们便证明了原命题成立。

## 实数域$\mathbb{R}$中根的存在性
### 定理
> 对于任意$n\in\mathbb{N}$，每个正实数都有唯一的正$n$次方根。

> 用符号表示，即：$\forall x\in\mathbb{R}$且$x>0$，$\forall n\in\mathbb{N}$，
$\exists$唯一的$y\in\mathbb{R}$，使得$y>0$且$y^n=x$。

### 证明
首先证明唯一性，这里使用反证法来加以证明。
我们假设某个实数$x$存在两个不相同的$n$次方根$y_1$和$y_2$，
即有$y_1^n=x$和$y_2^2=x$同时成立。
不失一般性地，我们假设$0<y_1<y_2$，由有序域公理可以推知$0<y_1^n<y_2^n$，
即有$x<x$成立，显然矛盾，故而唯一性得证。

上面的证明过程直接假设正$n$次方根存在，但事实上其存在性需要证明。
我们构建出如下形式的集合：
$$
  E = \{t\in\mathbb{R}|t>0且t^n<x\}
$$
为了使用实数域的最小上界性，我们首先要证明集合$E$非空，
我们可以取$t_0=x/(x+1)$，
因为$0<t_0^n\le t_0<x$，所以$t_0\in E$。
然后要证明集合$E$存在上界，我们可以令$t_1=x+1$，
显然我们有$t^n_1\ge t_1>x$。
两相结合，我们认为集合$E$存在上确界，记为$y=\sup E$。

如果可以证明$y$既不能大于$\sqrt[n]{x}$，也不能小于$\sqrt[n]{x}$，
那就只能有$y=\sqrt[n]{x}$，由于前文已经证明了$y=\sup E$，
则$\sqrt[n]{x}$存在。
当然，在证明$\sqrt[n]{x}$存在之前，我们还不能直接使用这一符号，
更为正式的说法是证明$y^n>x$和$y^n<x$均不成立。

使用反证法证明$y^n<x$不成立。
我们首先假设$y^n<x$，即$y\in E$。
如果存在$h>0$，且有$y+h\in E$，则$y$不为集合$E$的上界，与$y$为上确界相矛盾。

注意到对于任意的$0<a<b$，都有
$$
  b^n-a^n=(b-a)\sum_{k=1}^nb^{n-k}a^{k-1}<(b-a)nb^{n-1}
$$

令$b=y+h$，$a=y$，则上式可化为：
$$
  \begin{split}
  (y+h)^n-y^n&<hn(y+h)^{n-1}\\
  (y+h)^n&<y^n+hn(y+h)^{n-1}
  \end{split}
$$
如果有$y^n+hn(y+h)^{n-1}<x$，则有$y^n<x$成立，命题得证。
这里我们取一个小于$1$的$h$，则可对上述不等式进行如下放缩：
$$
  y^n+hn(y+h)^{n-1}<y^n+hn(y+1)^{n-1}
$$
取$h<(x-y^n)/(n(y+1)^{n-1})$，便有$y^n+hn(y+1)^{n-1}<x$。
显然$h>0$，所以我们只要取
$$
  h <\min\left\{1， \frac{x-y^n}{n(y+1)^{n-1}}\right\}
$$
由此完成了这一半的证明。

现在再使用反证法证明$y^n>x$不成立。
我们首先假设$y^n>x$成立，那么显然$y$就是集合$E$的一个上界，
如果我们能够找到一个$k>0$，使得$y-k$同样也是集合$E$的一个上界，
那便与$y$是集合$E$的上确界相矛盾。

令前文不等式当中的$a=y$，$b=y-k$，可以有：
$$
  \begin{split}
    y^n-(y-k)^n&<kny^{n-1}\\
    (y-k)^n&>y^n-kny^{n-1}
  \end{split}
$$
如果有$y^n-kny^{n-1}=x$，即$k=(y^n-x)/(ny^{n-1})$，
由假设$y^n>x$保证了$k>0$，且有$y-k>0$，
故而$(y-k)^n>x$成立，由此便完成了另外半部分的证明。

综上所述，原命题得证，即每个正实数都存在一个唯一的正$n$次方根。